[env]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200
lib_deps =
  bblanchon/ArduinoJson@^7.0.0
build_flags =
  -D ARDUINO_USB_CDC_ON_BOOT=1
  -D ARDUINO_USB_MODE=1

[env:esp32_c3_super_mini]

[env:wifi_message]

[env:wifi_diagnostic]
build_flags =
  ${env.build_flags}
  -D ALIVE_WIFI_DIAGNOSTIC=1

[env:hardware_test]
build_flags =
  ${env.build_flags}
  -D ALIVE_HARDWARE_TEST=1

[env:message_test]
build_flags =
  ${env.build_flags}
  -D ALIVE_MESSAGE_TEST=1

[env:serial_message]
build_flags =
  ${env.build_flags}
  -D ALIVE_SERIAL_MESSAGE=1

[env:silence_test]
build_flags =
  ${env.build_flags}
  -D ALIVE_SILENCE_TEST=1
