"""Generate the shared DDS tables. No playback or device access."""
import math
from pathlib import Path

root = Path(__file__).resolve().parents[4]
sine = [int(32767 * math.sin(2 * math.pi * i / 1024)) for i in range(1025)]
envelope = [int(32767 * math.sin(math.pi * i / 1024) ** 2) for i in range(1025)]
def values(samples):
    return ',\n'.join(','.join(map(str, samples[i:i+32])) for i in range(0, len(samples), 32))
Path(__file__).with_name('beacon_tables.h').write_text('// Generated by generate_beacon.py.\n' + '\n'.join(f'static const int16_t {name}[1025] = {{\n{values(samples)}\n}};' for name, samples in [('sine', sine), ('envelope', envelope)]) + '\n')
(root / 'web/src/audio/beaconTables.ts').write_text('// Generated by generate_beacon.py.\n' + '\n'.join(f'export const {name} = new Int16Array([\n{values(samples)}\n]);' for name, samples in [('sine', sine), ('envelope', envelope)]) + '\n')
